/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\clk_divider" *)
(* src = "clk_divider.v:2.1-23.10" *)
module \$paramod\clk_divider\div_value=s32'00000000000000000000000000000100 (clk_in, rst, clk_out);
  (* src = "clk_divider.v:8.5-22.8" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "clk_divider.v:3.17-3.23" *)
  input clk_in;
  wire clk_in;
  (* init = 1'h0 *)
  (* src = "clk_divider.v:5.17-5.24" *)
  output clk_out;
  wire clk_out;
  (* init = 4'h0 *)
  (* src = "clk_divider.v:7.15-7.20" *)
  wire [3:0] count;
  (* src = "clk_divider.v:4.17-4.20" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(count[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(rst),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor4bb_1 _12_ (
    .A(count[3]),
    .B(count[2]),
    .C_N(count[0]),
    .D_N(count[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(clk_out),
    .B(_07_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xor2_1 _14_ (
    .A(count[0]),
    .B(count[1]),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__nand3_1 _15_ (
    .A(count[0]),
    .B(count[1]),
    .C(count[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a31oi_1 _16_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[3]),
    .B1(count[2]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _17_ (
    .A(_08_),
    .SLEEP(_09_),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(count[3]),
    .B(_08_),
    .Y(_00_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(rst),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(rst),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(rst),
    .Y(_05_)
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk_in),
    .D(_06_),
    .Q(clk_out),
    .RESET_B(_01_)
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(clk_in),
    .D(_00_[0]),
    .Q(count[0]),
    .RESET_B(_02_)
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk_in),
    .D(_00_[1]),
    .Q(count[1]),
    .RESET_B(_03_)
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk_in),
    .D(_00_[2]),
    .Q(count[2]),
    .RESET_B(_04_)
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(clk_in),
    .D(_00_[3]),
    .Q(count[3]),
    .RESET_B(_05_)
  );
endmodule

(* dynports =  1  *)
(* hdlname = "\\lfsr" *)
(* src = "lfsr.v:3.1-18.10" *)
module \$paramod\lfsr\WIDTH=s32'00000000000000000000000000001010 (clk, rst, rnd);
  (* src = "lfsr.v:9.5-16.8" *)
  wire [9:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "lfsr.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "lfsr.v:6.28-6.31" *)
  output [9:0] rnd;
  wire [9:0] rnd;
  (* src = "lfsr.v:5.17-5.20" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(rst),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(rnd[6]),
    .B(rnd[9]),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _13_ (
    .A(rst),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _14_ (
    .A(rst),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(rst),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(rst),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(rst),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(rst),
    .Y(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(rst),
    .Y(_10_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _22_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(rnd[0]),
    .SET_B(_01_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _23_ (
    .CLK(clk),
    .D(rnd[0]),
    .Q(rnd[1]),
    .SET_B(_02_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _24_ (
    .CLK(clk),
    .D(rnd[1]),
    .Q(rnd[2]),
    .SET_B(_03_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _25_ (
    .CLK(clk),
    .D(rnd[2]),
    .Q(rnd[3]),
    .SET_B(_04_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _26_ (
    .CLK(clk),
    .D(rnd[3]),
    .Q(rnd[4]),
    .SET_B(_05_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _27_ (
    .CLK(clk),
    .D(rnd[4]),
    .Q(rnd[5]),
    .SET_B(_06_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _28_ (
    .CLK(clk),
    .D(rnd[5]),
    .Q(rnd[6]),
    .SET_B(_07_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _29_ (
    .CLK(clk),
    .D(rnd[6]),
    .Q(rnd[7]),
    .SET_B(_08_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _30_ (
    .CLK(clk),
    .D(rnd[7]),
    .Q(rnd[8]),
    .SET_B(_09_)
  );
  (* src = "lfsr.v:9.5-16.8" *)
  sky130_fd_sc_hd__dfstp_2 _31_ (
    .CLK(clk),
    .D(rnd[8]),
    .Q(rnd[9]),
    .SET_B(_10_)
  );
  assign _00_[9:1] = rnd[8:0];
endmodule

(* src = "barrel_shifter.v:3.1-23.10" *)
module barrel_shifter(data_in, shift_amt, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "barrel_shifter.v:4.23-4.30" *)
  input [9:0] data_in;
  wire [9:0] data_in;
  (* src = "barrel_shifter.v:6.23-6.31" *)
  output [9:0] data_out;
  wire [9:0] data_out;
  (* src = "barrel_shifter.v:5.23-5.32" *)
  input [2:0] shift_amt;
  wire [2:0] shift_amt;
  sky130_fd_sc_hd__and3_1 _39_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor3_1 _40_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a22o_1 _41_ (
    .A1(data_in[1]),
    .A2(_00_),
    .B1(_01_),
    .B2(data_in[0]),
    .X(data_out[0])
  );
  sky130_fd_sc_hd__nor3b_1 _42_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C_N(shift_amt[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a222oi_1 _43_ (
    .A1(data_in[1]),
    .A2(_01_),
    .B1(_02_),
    .B2(data_in[0]),
    .C1(data_in[2]),
    .C2(_00_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(_03_),
    .Y(data_out[1])
  );
  sky130_fd_sc_hd__nor3b_1 _45_ (
    .A(shift_amt[2]),
    .B(shift_amt[0]),
    .C_N(shift_amt[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(data_in[2]),
    .B(_01_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a222oi_1 _47_ (
    .A1(data_in[1]),
    .A2(_02_),
    .B1(_04_),
    .B2(data_in[0]),
    .C1(data_in[3]),
    .C2(_00_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(_05_),
    .B(_06_),
    .Y(data_out[2])
  );
  sky130_fd_sc_hd__and3b_1 _49_ (
    .A_N(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a22oi_1 _50_ (
    .A1(data_in[3]),
    .A2(_01_),
    .B1(_07_),
    .B2(data_in[0]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a222oi_1 _51_ (
    .A1(data_in[4]),
    .A2(_00_),
    .B1(_02_),
    .B2(data_in[2]),
    .C1(data_in[1]),
    .C2(_04_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _52_ (
    .A(_08_),
    .B(_09_),
    .Y(data_out[3])
  );
  sky130_fd_sc_hd__nor3b_1 _53_ (
    .A(shift_amt[1]),
    .B(shift_amt[0]),
    .C_N(shift_amt[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a222oi_1 _54_ (
    .A1(data_in[1]),
    .A2(_07_),
    .B1(_10_),
    .B2(data_in[0]),
    .C1(data_in[5]),
    .C2(_00_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a222oi_1 _55_ (
    .A1(data_in[4]),
    .A2(_01_),
    .B1(_02_),
    .B2(data_in[3]),
    .C1(data_in[2]),
    .C2(_04_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _56_ (
    .A(_11_),
    .B(_12_),
    .Y(data_out[4])
  );
  sky130_fd_sc_hd__and3b_1 _57_ (
    .A_N(shift_amt[1]),
    .B(shift_amt[0]),
    .C(shift_amt[2]),
    .X(_13_)
  );
  sky130_fd_sc_hd__a222oi_1 _58_ (
    .A1(data_in[4]),
    .A2(_02_),
    .B1(_07_),
    .B2(data_in[2]),
    .C1(data_in[0]),
    .C2(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a22oi_1 _59_ (
    .A1(data_in[6]),
    .A2(_00_),
    .B1(_10_),
    .B2(data_in[1]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a22oi_1 _60_ (
    .A1(data_in[5]),
    .A2(_01_),
    .B1(_04_),
    .B2(data_in[3]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand3_1 _61_ (
    .A(_14_),
    .B(_15_),
    .C(_16_),
    .Y(data_out[5])
  );
  sky130_fd_sc_hd__and3b_1 _62_ (
    .A_N(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .X(_17_)
  );
  sky130_fd_sc_hd__a22oi_1 _63_ (
    .A1(data_in[1]),
    .A2(_13_),
    .B1(_17_),
    .B2(data_in[0]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a22oi_1 _64_ (
    .A1(data_in[5]),
    .A2(_02_),
    .B1(_04_),
    .B2(data_in[4]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__and4_1 _65_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D(data_in[7]),
    .X(_20_)
  );
  sky130_fd_sc_hd__nor4b_1 _66_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D_N(data_in[6]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor4bb_1 _67_ (
    .A(shift_amt[1]),
    .B(shift_amt[0]),
    .C_N(data_in[2]),
    .D_N(shift_amt[2]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a2111oi_0 _68_ (
    .A1(data_in[3]),
    .A2(_07_),
    .B1(_20_),
    .C1(_21_),
    .D1(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nand3_1 _69_ (
    .A(_18_),
    .B(_19_),
    .C(_23_),
    .Y(data_out[6])
  );
  sky130_fd_sc_hd__a22oi_1 _70_ (
    .A1(data_in[2]),
    .A2(_13_),
    .B1(_17_),
    .B2(data_in[1]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a22oi_1 _71_ (
    .A1(data_in[6]),
    .A2(_02_),
    .B1(_04_),
    .B2(data_in[5]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__and4_1 _72_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D(data_in[8]),
    .X(_26_)
  );
  sky130_fd_sc_hd__nor4b_1 _73_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D_N(data_in[7]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor4bb_1 _74_ (
    .A(shift_amt[1]),
    .B(shift_amt[0]),
    .C_N(data_in[3]),
    .D_N(shift_amt[2]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a2111oi_0 _75_ (
    .A1(data_in[4]),
    .A2(_07_),
    .B1(_26_),
    .C1(_27_),
    .D1(_28_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nand3_1 _76_ (
    .A(_24_),
    .B(_25_),
    .C(_29_),
    .Y(data_out[7])
  );
  sky130_fd_sc_hd__a22oi_1 _77_ (
    .A1(data_in[3]),
    .A2(_13_),
    .B1(_17_),
    .B2(data_in[2]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a22oi_1 _78_ (
    .A1(data_in[7]),
    .A2(_02_),
    .B1(_04_),
    .B2(data_in[6]),
    .Y(_31_)
  );
  sky130_fd_sc_hd__and4_1 _79_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D(data_in[9]),
    .X(_32_)
  );
  sky130_fd_sc_hd__nor4b_1 _80_ (
    .A(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .D_N(data_in[8]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor4bb_1 _81_ (
    .A(shift_amt[1]),
    .B(shift_amt[0]),
    .C_N(data_in[4]),
    .D_N(shift_amt[2]),
    .Y(_34_)
  );
  sky130_fd_sc_hd__a2111oi_0 _82_ (
    .A1(data_in[5]),
    .A2(_07_),
    .B1(_32_),
    .C1(_33_),
    .D1(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__nand3_1 _83_ (
    .A(_30_),
    .B(_31_),
    .C(_35_),
    .Y(data_out[8])
  );
  sky130_fd_sc_hd__a222oi_1 _84_ (
    .A1(data_in[8]),
    .A2(_02_),
    .B1(_07_),
    .B2(data_in[6]),
    .C1(data_in[4]),
    .C2(_13_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__a22oi_1 _85_ (
    .A1(data_in[5]),
    .A2(_10_),
    .B1(_17_),
    .B2(data_in[3]),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a22oi_1 _86_ (
    .A1(data_in[9]),
    .A2(_01_),
    .B1(_04_),
    .B2(data_in[7]),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nand3_1 _87_ (
    .A(_36_),
    .B(_37_),
    .C(_38_),
    .Y(data_out[9])
  );
endmodule

(* src = "parity_gen.v:3.1-10.10" *)
module parity_gen(data_in, parity);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "parity_gen.v:4.23-4.30" *)
  input [9:0] data_in;
  wire [9:0] data_in;
  (* src = "parity_gen.v:5.23-5.29" *)
  output parity;
  wire parity;
  sky130_fd_sc_hd__xor2_1 _07_ (
    .A(data_in[7]),
    .B(data_in[6]),
    .X(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _08_ (
    .A(data_in[5]),
    .B(data_in[4]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(data_in[3]),
    .B(data_in[2]),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _11_ (
    .A(data_in[1]),
    .B(data_in[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _12_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _13_ (
    .A(data_in[9]),
    .B(data_in[8]),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor3_1 _14_ (
    .A(_02_),
    .B(_05_),
    .C(_06_),
    .X(parity)
  );
endmodule

(* top =  1  *)
(* src = "rtl_topmodule.v:2.1-64.10" *)
module rtl_topmodule(clk, rst, A, C, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  (* src = "rtl_topmodule.v:5.24-5.25" *)
  input [9:0] A;
  wire [9:0] A;
  (* src = "rtl_topmodule.v:9.16-9.21" *)
  wire [9:0] A_reg;
  (* src = "rtl_topmodule.v:6.24-6.25" *)
  input [8:0] C;
  wire [8:0] C;
  (* src = "rtl_topmodule.v:10.16-10.21" *)
  wire [8:0] C_reg;
  (* src = "rtl_topmodule.v:3.24-3.27" *)
  input clk;
  wire clk;
  (* src = "rtl_topmodule.v:22.10-22.17" *)
  wire clk_div;
  (* src = "rtl_topmodule.v:35.16-35.24" *)
  wire [9:0] lfsr_out;
  (* src = "rtl_topmodule.v:7.24-7.27" *)
  output [10:0] out;
  wire [10:0] out;
  (* src = "rtl_topmodule.v:42.10-42.20" *)
  wire parity_out;
  (* src = "rtl_topmodule.v:4.24-4.27" *)
  input rst;
  wire rst;
  (* src = "rtl_topmodule.v:28.16-28.27" *)
  wire [9:0] shifter_out;
  sky130_fd_sc_hd__or3_1 _054_ (
    .A(C_reg[4]),
    .B(C_reg[3]),
    .C(C_reg[2]),
    .X(_038_)
  );
  sky130_fd_sc_hd__or4_1 _055_ (
    .A(C_reg[6]),
    .B(C_reg[5]),
    .C(C_reg[1]),
    .D(C_reg[0]),
    .X(_039_)
  );
  sky130_fd_sc_hd__o21ai_0 _056_ (
    .A1(_038_),
    .A2(_039_),
    .B1(C_reg[7]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _057_ (
    .A_N(C_reg[8]),
    .B(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor3_1 _058_ (
    .A(C_reg[3]),
    .B(C_reg[1]),
    .C(C_reg[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor4bb_1 _059_ (
    .A(C_reg[7]),
    .B(C_reg[4]),
    .C_N(C_reg[5]),
    .D_N(C_reg[6]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a31o_1 _060_ (
    .A1(C_reg[2]),
    .A2(_042_),
    .A3(_043_),
    .B1(C_reg[8]),
    .X(_044_)
  );
  sky130_fd_sc_hd__a311oi_1 _061_ (
    .A1(C_reg[6]),
    .A2(C_reg[5]),
    .A3(_038_),
    .B1(_044_),
    .C1(C_reg[7]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a22oi_1 _062_ (
    .A1(lfsr_out[1]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__a211oi_1 _063_ (
    .A1(C_reg[1]),
    .A2(C_reg[0]),
    .B1(C_reg[3]),
    .C1(C_reg[2]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _064_ (
    .A(C_reg[5]),
    .B(C_reg[4]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor3_1 _065_ (
    .A(C_reg[8]),
    .B(C_reg[6]),
    .C(C_reg[7]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _066_ (
    .A1(_047_),
    .A2(_048_),
    .B1(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2b_1 _067_ (
    .A_N(rst),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _068_ (
    .A(_046_),
    .B(_051_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a22oi_1 _069_ (
    .A1(lfsr_out[2]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[2]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _070_ (
    .A(_051_),
    .B(_052_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a22oi_1 _071_ (
    .A1(lfsr_out[3]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[3]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _072_ (
    .A(_051_),
    .B(_053_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a22oi_1 _073_ (
    .A1(lfsr_out[4]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _074_ (
    .A(_051_),
    .B(_029_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a22oi_1 _075_ (
    .A1(lfsr_out[5]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[5]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_1 _076_ (
    .A(_051_),
    .B(_030_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a22oi_1 _077_ (
    .A1(lfsr_out[6]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[6]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _078_ (
    .A(_051_),
    .B(_031_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a22oi_1 _079_ (
    .A1(lfsr_out[7]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[7]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(_051_),
    .B(_032_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__a22oi_1 _081_ (
    .A1(lfsr_out[8]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[8]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _082_ (
    .A(_051_),
    .B(_033_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a22oi_1 _083_ (
    .A1(lfsr_out[9]),
    .A2(_041_),
    .B1(_045_),
    .B2(shifter_out[9]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(_051_),
    .B(_034_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _085_ (
    .A(C[0]),
    .SLEEP(rst),
    .X(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _086_ (
    .A(C[1]),
    .SLEEP(rst),
    .X(_010_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _087_ (
    .A(C[2]),
    .SLEEP(rst),
    .X(_011_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _088_ (
    .A(C[3]),
    .SLEEP(rst),
    .X(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _089_ (
    .A(C[4]),
    .SLEEP(rst),
    .X(_013_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _090_ (
    .A(C[5]),
    .SLEEP(rst),
    .X(_014_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _091_ (
    .A(C[6]),
    .SLEEP(rst),
    .X(_015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _092_ (
    .A(C[7]),
    .SLEEP(rst),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _093_ (
    .A(C[8]),
    .SLEEP(rst),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _094_ (
    .A0(parity_out),
    .A1(lfsr_out[0]),
    .S(_041_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2i_1 _095_ (
    .A0(_035_),
    .A1(shifter_out[0]),
    .S(_045_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(clk_div),
    .B(_050_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a211oi_1 _097_ (
    .A1(_050_),
    .A2(_036_),
    .B1(_037_),
    .C1(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(A[0]),
    .SLEEP(rst),
    .X(_019_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _099_ (
    .A(A[1]),
    .SLEEP(rst),
    .X(_020_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _100_ (
    .A(A[2]),
    .SLEEP(rst),
    .X(_021_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _101_ (
    .A(A[3]),
    .SLEEP(rst),
    .X(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _102_ (
    .A(A[4]),
    .SLEEP(rst),
    .X(_023_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _103_ (
    .A(A[5]),
    .SLEEP(rst),
    .X(_024_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _104_ (
    .A(A[6]),
    .SLEEP(rst),
    .X(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _105_ (
    .A(A[7]),
    .SLEEP(rst),
    .X(_026_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _106_ (
    .A(A[8]),
    .SLEEP(rst),
    .X(_027_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _107_ (
    .A(A[9]),
    .SLEEP(rst),
    .X(_028_)
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _108_ (
    .CLK(clk),
    .D(_000_),
    .Q(out[1])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _109_ (
    .CLK(clk),
    .D(_001_),
    .Q(out[2])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _110_ (
    .CLK(clk),
    .D(_002_),
    .Q(out[3])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _111_ (
    .CLK(clk),
    .D(_003_),
    .Q(out[4])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _112_ (
    .CLK(clk),
    .D(_004_),
    .Q(out[5])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _113_ (
    .CLK(clk),
    .D(_005_),
    .Q(out[6])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _114_ (
    .CLK(clk),
    .D(_006_),
    .Q(out[7])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _115_ (
    .CLK(clk),
    .D(_007_),
    .Q(out[8])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(clk),
    .D(_008_),
    .Q(out[9])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(clk),
    .D(_009_),
    .Q(C_reg[0])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(clk),
    .D(_010_),
    .Q(C_reg[1])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(clk),
    .D(_011_),
    .Q(C_reg[2])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(_012_),
    .Q(C_reg[3])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(_013_),
    .Q(C_reg[4])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(_014_),
    .Q(C_reg[5])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_015_),
    .Q(C_reg[6])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_016_),
    .Q(C_reg[7])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(_017_),
    .Q(C_reg[8])
  );
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(_018_),
    .Q(out[0])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(_019_),
    .Q(A_reg[0])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(clk),
    .D(_020_),
    .Q(A_reg[1])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _129_ (
    .CLK(clk),
    .D(_021_),
    .Q(A_reg[2])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _130_ (
    .CLK(clk),
    .D(_022_),
    .Q(A_reg[3])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _131_ (
    .CLK(clk),
    .D(_023_),
    .Q(A_reg[4])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _132_ (
    .CLK(clk),
    .D(_024_),
    .Q(A_reg[5])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _133_ (
    .CLK(clk),
    .D(_025_),
    .Q(A_reg[6])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _134_ (
    .CLK(clk),
    .D(_026_),
    .Q(A_reg[7])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _135_ (
    .CLK(clk),
    .D(_027_),
    .Q(A_reg[8])
  );
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfxtp_1 _136_ (
    .CLK(clk),
    .D(_028_),
    .Q(A_reg[9])
  );
  (* src = "rtl_topmodule.v:23.34-26.6" *)
  \$paramod\clk_divider\div_value=s32'00000000000000000000000000000100  u1 (
    .clk_in(clk),
    .clk_out(clk_div)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_topmodule.v:29.20-33.6" *)
  barrel_shifter u2 (
    .data_in(A_reg),
    .data_out(shifter_out),
    .shift_amt(C_reg[2:0])
  );
  (* src = "rtl_topmodule.v:36.24-40.6" *)
  \$paramod\lfsr\WIDTH=s32'00000000000000000000000000001010  u3 (
    .clk(clk),
    .rnd(lfsr_out),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_topmodule.v:43.16-46.6" *)
  parity_gen u4 (
    .data_in(A_reg),
    .parity(parity_out)
  );
  assign out[10] = 1'h0;
endmodule
