/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\clk_divider" *)
(* src = "clk_divider.v:2.1-23.10" *)
module \$paramod\clk_divider\div_value=s32'00000000000000000000000000000100 (clk_in, rst, clk_out);
  (* src = "clk_divider.v:8.5-22.8" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "clk_divider.v:17.28-17.36" *)
  wire _05_;
  (* src = "clk_divider.v:3.17-3.23" *)
  input clk_in;
  wire clk_in;
  (* src = "clk_divider.v:5.17-5.24" *)
  output clk_out;
  reg clk_out = 1'h0;
  (* src = "clk_divider.v:7.15-7.20" *)
  reg [3:0] count = 4'h0;
  (* src = "clk_divider.v:4.17-4.20" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _06_ (
    .A(count[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _07_ (
    .A(clk_out),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand3b_1 _08_ (
    .A_N(count[2]),
    .B(count[0]),
    .C(count[1]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _09_ (
    .A(count[3]),
    .SLEEP(_02_),
    .X(_01_)
  );
  sky130_fd_sc_hd__xor2_1 _10_ (
    .A(count[1]),
    .B(count[0]),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__a21boi_0 _11_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1_N(count[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(count[3]),
    .A1(_03_),
    .S(_02_),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__nand3_1 _13_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _14_ (
    .A(count[3]),
    .B(_04_),
    .Y(_00_[3])
  );
  (* src = "clk_divider.v:8.5-22.8" *)
  always @(posedge clk_in, posedge rst)
    if (rst) clk_out <= 1'h0;
    else if (!_01_) clk_out <= _05_;
  (* src = "clk_divider.v:8.5-22.8" *)
  always @(posedge clk_in, posedge rst)
    if (rst) count[0] <= 1'h0;
    else count[0] <= _00_[0];
  (* src = "clk_divider.v:8.5-22.8" *)
  always @(posedge clk_in, posedge rst)
    if (rst) count[1] <= 1'h0;
    else count[1] <= _00_[1];
  (* src = "clk_divider.v:8.5-22.8" *)
  always @(posedge clk_in, posedge rst)
    if (rst) count[2] <= 1'h0;
    else count[2] <= _00_[2];
  (* src = "clk_divider.v:8.5-22.8" *)
  always @(posedge clk_in, posedge rst)
    if (rst) count[3] <= 1'h0;
    else count[3] <= _00_[3];
endmodule

(* dynports =  1  *)
(* hdlname = "\\lfsr" *)
(* src = "lfsr.v:3.1-18.10" *)
module \$paramod\lfsr\WIDTH=s32'00000000000000000000000000001010 (clk, rst, rnd);
  (* src = "lfsr.v:9.5-16.8" *)
  wire [9:0] _00_;
  (* src = "lfsr.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "lfsr.v:6.28-6.31" *)
  output [9:0] rnd;
  reg [9:0] rnd;
  (* src = "lfsr.v:5.17-5.20" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__xor2_1 _01_ (
    .A(rnd[9]),
    .B(rnd[6]),
    .X(_00_[0])
  );
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[0] <= 1'h1;
    else rnd[0] <= _00_[0];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[1] <= 1'h1;
    else rnd[1] <= rnd[0];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[2] <= 1'h1;
    else rnd[2] <= rnd[1];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[3] <= 1'h1;
    else rnd[3] <= rnd[2];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[4] <= 1'h1;
    else rnd[4] <= rnd[3];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[5] <= 1'h1;
    else rnd[5] <= rnd[4];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[6] <= 1'h1;
    else rnd[6] <= rnd[5];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[7] <= 1'h1;
    else rnd[7] <= rnd[6];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[8] <= 1'h1;
    else rnd[8] <= rnd[7];
  (* src = "lfsr.v:9.5-16.8" *)
  always @(posedge clk, posedge rst)
    if (rst) rnd[9] <= 1'h1;
    else rnd[9] <= rnd[8];
  assign _00_[9:1] = rnd[8:0];
endmodule

(* src = "barrel_shifter.v:3.1-23.10" *)
module barrel_shifter(data_in, shift_amt, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  (* src = "barrel_shifter.v:4.23-4.30" *)
  input [9:0] data_in;
  wire [9:0] data_in;
  (* src = "barrel_shifter.v:6.23-6.31" *)
  output [9:0] data_out;
  wire [9:0] data_out;
  (* src = "barrel_shifter.v:5.23-5.32" *)
  input [2:0] shift_amt;
  wire [2:0] shift_amt;
  sky130_fd_sc_hd__and3_1 _39_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor3_1 _40_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a22o_1 _41_ (
    .A1(data_in[1]),
    .A2(_00_),
    .B1(_01_),
    .B2(data_in[0]),
    .X(data_out[0])
  );
  sky130_fd_sc_hd__nor3b_1 _42_ (
    .A(shift_amt[1]),
    .B(shift_amt[2]),
    .C_N(shift_amt[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a222oi_1 _43_ (
    .A1(data_in[2]),
    .A2(_00_),
    .B1(_01_),
    .B2(data_in[1]),
    .C1(data_in[0]),
    .C2(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(_03_),
    .Y(data_out[1])
  );
  sky130_fd_sc_hd__nor3b_1 _45_ (
    .A(shift_amt[0]),
    .B(shift_amt[2]),
    .C_N(shift_amt[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(data_in[2]),
    .B(_01_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a222oi_1 _47_ (
    .A1(data_in[3]),
    .A2(_00_),
    .B1(_02_),
    .B2(data_in[1]),
    .C1(data_in[0]),
    .C2(_04_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(_05_),
    .B(_06_),
    .Y(data_out[2])
  );
  sky130_fd_sc_hd__and3b_1 _49_ (
    .A_N(shift_amt[2]),
    .B(shift_amt[1]),
    .C(shift_amt[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a22oi_1 _50_ (
    .A1(data_in[3]),
    .A2(_01_),
    .B1(_04_),
    .B2(data_in[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a222oi_1 _51_ (
    .A1(data_in[4]),
    .A2(_00_),
    .B1(_02_),
    .B2(data_in[2]),
    .C1(data_in[0]),
    .C2(_07_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand2_1 _52_ (
    .A(_08_),
    .B(_09_),
    .Y(data_out[3])
  );
  sky130_fd_sc_hd__nor3b_1 _53_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C_N(shift_amt[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a222oi_1 _54_ (
    .A1(data_in[3]),
    .A2(_02_),
    .B1(_04_),
    .B2(data_in[2]),
    .C1(data_in[1]),
    .C2(_07_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a222oi_1 _55_ (
    .A1(data_in[5]),
    .A2(_00_),
    .B1(_01_),
    .B2(data_in[4]),
    .C1(data_in[0]),
    .C2(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand2_1 _56_ (
    .A(_11_),
    .B(_12_),
    .Y(data_out[4])
  );
  sky130_fd_sc_hd__a222oi_1 _57_ (
    .A1(data_in[6]),
    .A2(_00_),
    .B1(_04_),
    .B2(data_in[3]),
    .C1(data_in[1]),
    .C2(_10_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a22oi_1 _58_ (
    .A1(data_in[4]),
    .A2(_02_),
    .B1(_07_),
    .B2(data_in[2]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__and3b_1 _59_ (
    .A_N(shift_amt[1]),
    .B(shift_amt[2]),
    .C(shift_amt[0]),
    .X(_15_)
  );
  sky130_fd_sc_hd__a22oi_1 _60_ (
    .A1(data_in[5]),
    .A2(_01_),
    .B1(_15_),
    .B2(data_in[0]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand3_1 _61_ (
    .A(_13_),
    .B(_14_),
    .C(_16_),
    .Y(data_out[5])
  );
  sky130_fd_sc_hd__and4b_1 _62_ (
    .A_N(shift_amt[2]),
    .B(data_in[3]),
    .C(shift_amt[0]),
    .D(shift_amt[1]),
    .X(_17_)
  );
  sky130_fd_sc_hd__and4_1 _63_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[7]),
    .X(_18_)
  );
  sky130_fd_sc_hd__and4b_1 _64_ (
    .A_N(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[0]),
    .X(_19_)
  );
  sky130_fd_sc_hd__a2111oi_0 _65_ (
    .A1(data_in[4]),
    .A2(_04_),
    .B1(_17_),
    .C1(_18_),
    .D1(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a22oi_1 _66_ (
    .A1(data_in[5]),
    .A2(_02_),
    .B1(_15_),
    .B2(data_in[1]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a22oi_1 _67_ (
    .A1(data_in[6]),
    .A2(_01_),
    .B1(_10_),
    .B2(data_in[2]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand3_1 _68_ (
    .A(_20_),
    .B(_21_),
    .C(_22_),
    .Y(data_out[6])
  );
  sky130_fd_sc_hd__and4b_1 _69_ (
    .A_N(shift_amt[2]),
    .B(data_in[4]),
    .C(shift_amt[0]),
    .D(shift_amt[1]),
    .X(_23_)
  );
  sky130_fd_sc_hd__and4_1 _70_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[8]),
    .X(_24_)
  );
  sky130_fd_sc_hd__and4b_1 _71_ (
    .A_N(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[1]),
    .X(_25_)
  );
  sky130_fd_sc_hd__a2111oi_0 _72_ (
    .A1(data_in[5]),
    .A2(_04_),
    .B1(_23_),
    .C1(_24_),
    .D1(_25_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a22oi_1 _73_ (
    .A1(data_in[6]),
    .A2(_02_),
    .B1(_15_),
    .B2(data_in[2]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a22oi_1 _74_ (
    .A1(data_in[7]),
    .A2(_01_),
    .B1(_10_),
    .B2(data_in[3]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand3_1 _75_ (
    .A(_26_),
    .B(_27_),
    .C(_28_),
    .Y(data_out[7])
  );
  sky130_fd_sc_hd__and4b_1 _76_ (
    .A_N(shift_amt[2]),
    .B(data_in[5]),
    .C(shift_amt[0]),
    .D(shift_amt[1]),
    .X(_29_)
  );
  sky130_fd_sc_hd__and4_1 _77_ (
    .A(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[9]),
    .X(_30_)
  );
  sky130_fd_sc_hd__and4b_1 _78_ (
    .A_N(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[2]),
    .X(_31_)
  );
  sky130_fd_sc_hd__a2111oi_0 _79_ (
    .A1(data_in[6]),
    .A2(_04_),
    .B1(_29_),
    .C1(_30_),
    .D1(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a22oi_1 _80_ (
    .A1(data_in[7]),
    .A2(_02_),
    .B1(_15_),
    .B2(data_in[3]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a22oi_1 _81_ (
    .A1(data_in[8]),
    .A2(_01_),
    .B1(_10_),
    .B2(data_in[4]),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nand3_1 _82_ (
    .A(_32_),
    .B(_33_),
    .C(_34_),
    .Y(data_out[8])
  );
  sky130_fd_sc_hd__nand4b_1 _83_ (
    .A_N(shift_amt[0]),
    .B(shift_amt[1]),
    .C(shift_amt[2]),
    .D(data_in[3]),
    .Y(_35_)
  );
  sky130_fd_sc_hd__a22oi_1 _84_ (
    .A1(data_in[8]),
    .A2(_02_),
    .B1(_07_),
    .B2(data_in[6]),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nand2_1 _85_ (
    .A(data_in[4]),
    .B(_15_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a222oi_1 _86_ (
    .A1(data_in[9]),
    .A2(_01_),
    .B1(_04_),
    .B2(data_in[7]),
    .C1(data_in[5]),
    .C2(_10_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nand4_1 _87_ (
    .A(_35_),
    .B(_36_),
    .C(_37_),
    .D(_38_),
    .Y(data_out[9])
  );
endmodule

(* src = "parity_gen.v:3.1-10.10" *)
module parity_gen(data_in, parity);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "parity_gen.v:4.23-4.30" *)
  input [9:0] data_in;
  wire [9:0] data_in;
  (* src = "parity_gen.v:5.23-5.29" *)
  output parity;
  wire parity;
  sky130_fd_sc_hd__xnor2_1 _07_ (
    .A(data_in[0]),
    .B(data_in[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _08_ (
    .A(data_in[2]),
    .B(data_in[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xnor2_1 _09_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _10_ (
    .A(data_in[4]),
    .B(data_in[5]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _11_ (
    .A(data_in[6]),
    .B(data_in[7]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _12_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(data_in[8]),
    .B(data_in[9]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor3_1 _14_ (
    .A(_02_),
    .B(_05_),
    .C(_06_),
    .X(parity)
  );
endmodule

(* top =  1  *)
(* src = "rtl_topmodule.v:2.1-64.10" *)
module rtl_topmodule(clk, rst, A, C, out);
  (* src = "rtl_topmodule.v:48.5-58.8" *)
  (* unused_bits = "0" *)
  wire [10:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "rtl_topmodule.v:5.24-5.25" *)
  input [9:0] A;
  wire [9:0] A;
  (* src = "rtl_topmodule.v:9.16-9.21" *)
  reg [9:0] A_reg;
  (* src = "rtl_topmodule.v:6.24-6.25" *)
  input [8:0] C;
  wire [8:0] C;
  (* src = "rtl_topmodule.v:10.16-10.21" *)
  reg [8:0] C_reg;
  (* src = "rtl_topmodule.v:3.24-3.27" *)
  input clk;
  wire clk;
  (* src = "rtl_topmodule.v:22.10-22.17" *)
  wire clk_div;
  (* src = "rtl_topmodule.v:35.16-35.24" *)
  wire [9:0] lfsr_out;
  (* src = "rtl_topmodule.v:7.24-7.27" *)
  output [10:0] out;
  wire [10:0] out;
  (* src = "rtl_topmodule.v:11.16-11.23" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9" *)
  wire [10:0] out_reg;
  (* src = "rtl_topmodule.v:42.10-42.20" *)
  wire parity_out;
  (* src = "rtl_topmodule.v:4.24-4.27" *)
  input rst;
  wire rst;
  (* src = "rtl_topmodule.v:28.16-28.27" *)
  wire [9:0] shifter_out;
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(C_reg[7]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(lfsr_out[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(C_reg[2]),
    .B(C_reg[3]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _25_ (
    .A(C_reg[0]),
    .B(C_reg[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _26_ (
    .A(C_reg[4]),
    .B(C_reg[5]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(_04_),
    .A2(_05_),
    .B1(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__or4_1 _28_ (
    .A(C_reg[6]),
    .B(C_reg[7]),
    .C(C_reg[8]),
    .D(_07_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nand2b_1 _29_ (
    .A_N(rst),
    .B(_08_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__o31a_1 _30_ (
    .A1(C_reg[2]),
    .A2(C_reg[3]),
    .A3(C_reg[4]),
    .B1(C_reg[5]),
    .X(_09_)
  );
  sky130_fd_sc_hd__a21oi_1 _31_ (
    .A1(C_reg[6]),
    .A2(_09_),
    .B1(C_reg[7]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor4bb_1 _32_ (
    .A(C_reg[3]),
    .B(C_reg[4]),
    .C_N(C_reg[5]),
    .D_N(C_reg[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(C_reg[0]),
    .B(C_reg[1]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a41oi_1 _34_ (
    .A1(C_reg[6]),
    .A2(_02_),
    .A3(_11_),
    .A4(_12_),
    .B1(C_reg[8]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and2_0 _35_ (
    .A(_10_),
    .B(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _36_ (
    .A(C_reg[6]),
    .B(C_reg[4]),
    .C(C_reg[5]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a31oi_1 _37_ (
    .A1(_04_),
    .A2(_12_),
    .A3(_15_),
    .B1(_02_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _38_ (
    .A(C_reg[8]),
    .SLEEP(_16_),
    .X(_17_)
  );
  sky130_fd_sc_hd__a22o_1 _39_ (
    .A1(shifter_out[1]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[1]),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__a22o_1 _40_ (
    .A1(shifter_out[2]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[2]),
    .X(_00_[2])
  );
  sky130_fd_sc_hd__a22o_1 _41_ (
    .A1(shifter_out[3]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[3]),
    .X(_00_[3])
  );
  sky130_fd_sc_hd__a22o_1 _42_ (
    .A1(shifter_out[4]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[4]),
    .X(_00_[4])
  );
  sky130_fd_sc_hd__a22o_1 _43_ (
    .A1(shifter_out[5]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[5]),
    .X(_00_[5])
  );
  sky130_fd_sc_hd__a22o_1 _44_ (
    .A1(shifter_out[6]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[6]),
    .X(_00_[6])
  );
  sky130_fd_sc_hd__a22o_1 _45_ (
    .A1(shifter_out[7]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[7]),
    .X(_00_[7])
  );
  sky130_fd_sc_hd__a22o_1 _46_ (
    .A1(shifter_out[8]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[8]),
    .X(_00_[8])
  );
  sky130_fd_sc_hd__a22o_1 _47_ (
    .A1(shifter_out[9]),
    .A2(_14_),
    .B1(_17_),
    .B2(lfsr_out[9]),
    .X(_00_[9])
  );
  sky130_fd_sc_hd__nor3_1 _48_ (
    .A(parity_out),
    .B(C_reg[8]),
    .C(_16_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a211o_1 _49_ (
    .A1(_03_),
    .A2(_17_),
    .B1(_18_),
    .C1(_14_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nand2_1 _50_ (
    .A(shifter_out[0]),
    .B(_14_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _51_ (
    .A(clk_div),
    .B(_08_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a31oi_1 _52_ (
    .A1(_08_),
    .A2(_19_),
    .A3(_20_),
    .B1(_21_),
    .Y(out_reg[0])
  );
  reg \out_reg[0] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (rst) \out_reg[0]  <= 1'h0;
    else \out_reg[0]  <= out_reg[0];
  assign out[0] = \out_reg[0] ;
  reg \out_reg[1] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[1]  <= 1'h0;
    else \out_reg[1]  <= _00_[1];
  assign out[1] = \out_reg[1] ;
  reg \out_reg[2] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[2]  <= 1'h0;
    else \out_reg[2]  <= _00_[2];
  assign out[2] = \out_reg[2] ;
  reg \out_reg[3] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[3]  <= 1'h0;
    else \out_reg[3]  <= _00_[3];
  assign out[3] = \out_reg[3] ;
  reg \out_reg[4] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[4]  <= 1'h0;
    else \out_reg[4]  <= _00_[4];
  assign out[4] = \out_reg[4] ;
  reg \out_reg[5] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[5]  <= 1'h0;
    else \out_reg[5]  <= _00_[5];
  assign out[5] = \out_reg[5] ;
  reg \out_reg[6] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[6]  <= 1'h0;
    else \out_reg[6]  <= _00_[6];
  assign out[6] = \out_reg[6] ;
  reg \out_reg[7] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[7]  <= 1'h0;
    else \out_reg[7]  <= _00_[7];
  assign out[7] = \out_reg[7] ;
  reg \out_reg[8] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[8]  <= 1'h0;
    else \out_reg[8]  <= _00_[8];
  assign out[8] = \out_reg[8] ;
  reg \out_reg[9] ;
  (* src = "rtl_topmodule.v:60.5-63.8" *)
  always @(posedge clk)
    if (_01_) \out_reg[9]  <= 1'h0;
    else \out_reg[9]  <= _00_[9];
  assign out[9] = \out_reg[9] ;
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[0] <= 1'h0;
    else A_reg[0] <= A[0];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[1] <= 1'h0;
    else A_reg[1] <= A[1];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[2] <= 1'h0;
    else A_reg[2] <= A[2];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[3] <= 1'h0;
    else A_reg[3] <= A[3];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[4] <= 1'h0;
    else A_reg[4] <= A[4];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[5] <= 1'h0;
    else A_reg[5] <= A[5];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[6] <= 1'h0;
    else A_reg[6] <= A[6];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[7] <= 1'h0;
    else A_reg[7] <= A[7];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[8] <= 1'h0;
    else A_reg[8] <= A[8];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) A_reg[9] <= 1'h0;
    else A_reg[9] <= A[9];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[0] <= 1'h0;
    else C_reg[0] <= C[0];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[1] <= 1'h0;
    else C_reg[1] <= C[1];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[2] <= 1'h0;
    else C_reg[2] <= C[2];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[3] <= 1'h0;
    else C_reg[3] <= C[3];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[4] <= 1'h0;
    else C_reg[4] <= C[4];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[5] <= 1'h0;
    else C_reg[5] <= C[5];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[6] <= 1'h0;
    else C_reg[6] <= C[6];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[7] <= 1'h0;
    else C_reg[7] <= C[7];
  (* src = "rtl_topmodule.v:12.5-20.8" *)
  always @(posedge clk)
    if (rst) C_reg[8] <= 1'h0;
    else C_reg[8] <= C[8];
  (* src = "rtl_topmodule.v:23.34-26.6" *)
  \$paramod\clk_divider\div_value=s32'00000000000000000000000000000100  u1 (
    .clk_in(clk),
    .clk_out(clk_div)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_topmodule.v:29.20-33.6" *)
  barrel_shifter u2 (
    .data_in(A_reg),
    .data_out(shifter_out),
    .shift_amt(C_reg[2:0])
  );
  (* src = "rtl_topmodule.v:36.24-40.6" *)
  \$paramod\lfsr\WIDTH=s32'00000000000000000000000000001010  u3 (
    .clk(clk),
    .rnd(lfsr_out),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl_topmodule.v:43.16-46.6" *)
  parity_gen u4 (
    .data_in(A_reg),
    .parity(parity_out)
  );
  assign _00_[10] = 1'h0;
  assign out[10] = 1'h0;
  assign out_reg[10] = 1'h0;
endmodule
